"use client";
import "../app/global.css";
import Navbar from "./component/Navbar";
import "../app/page.css";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

import Image from "next/image";
import menuImage from "../../../public/menu.png";
import useApnaStore from "./store/store";
import Link from "next/link";
import SideBar from "./component/SideBar";
import React from "react";

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-primary ">
        <div className="maindiv flex flex-row  ">
          <div id="page_hold_div" className="">{children}</div>
          <SideBar></SideBar>
        </div>
      </body>
    </html>
  );
}
